// CDL — modules/procurement.js
import { SUPABASE_URL, SUPABASE_ANON_KEY, SITES } from "../config.js";
import { logAudit } from "./audit_core.js";
import { ROLES } from "./roles.js";
import { showToast, showModal, closeModal } from "../app.js";

const PROCUREMENT_FLOW = ["pending","pm_approved","am_approved","finance_approved","processing","ordered","delivered"];

export async function renderProcurement(container, user) {
  const role = ROLES[user.role] || {};
  const canCreate = ["project_manager","admin","asset_manager","procurement_officer"].includes(user.role);
  const siteFilter = role.siteScope === "assigned" ? (user.site_ids||[]) : SITES.map(s=>s.id);
  container.innerHTML = `<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:24px;"><div><h1 style="font-size:24px;font-weight:700;">Procurement</h1><p style="color:var(--text-200);font-size:14px;">Purchase requests, approvals & supplier management</p></div>${canCreate?`<button onclick="window._procOpenNew()" class="btn btn-gold">+ New Purchase Request</button>`:""}</div><div id="proc-tabs" style="display:flex;gap:4px;margin-bottom:20px;flex-wrap:wrap;">${["Pending","PM Approved","AM Approved","Finance Approved","Processing","Ordered","Delivered"].map((t,i)=>`<button onclick="window._procLoad('${t.toLowerCase().replace(/ /g,"_")}')" id="proc-tab-${t.toLowerCase().replace(/ /g,"_")}" style="padding:6px 14px;border-radius:8px;border:none;cursor:pointer;font-size:12px;font-weight:500;${i===0?"background:var(--gold);color:#0a0c10;":"background:var(--bg-600);color:var(--text-200);"}">${t}</button>`).join("")}</div><div id="proc-list"><div class="spinner" style="margin:60px auto;"></div></div>`;
  window._procLoad=(status)=>{"pending","pm_approved","am_approved","finance_approved","processing","ordered","delivered".forEach(s=>{const b=document.getElementById(`proc-tab-${s}`);if(b){b.style.background=s===status?"var(--gold)":"var(--bg-600)";b.style.color=s===status?"#0a0c10":"var(--text-200)";}});fetchProcurement(user,siteFilter,status);};
  window._procOpenNew=()=>openProcurementModal(user,siteFilter);
  fetchProcurement(user,siteFilter,"pending");
}

async function fetchProcurement(user,siteFilter,status) {
  const list=document.getElementById("proc-list");if(!list)return;list.innerHTML=`<div class="spinner" style="margin:60px auto;"></div>`;
  let q=`${SUPABASE_URL}/rest/v1/procurement?status=eq.${status}&select=*,sites(name)&order=created_at.desc&limit=50`;if(siteFilter.length)q+=`&site_id=in.(${siteFilter.join(",")})`;
  try {
    const res=await fetch(q,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`}});const orders=await res.json();
    if(!orders.length){list.innerHTML=`<div class="card" style="text-align:center;padding:40px;color:var(--text-300);">No ${status.replace(/_/g," ")} requests</div>`;return;}
    list.innerHTML=orders.map(o=>{const items=o.items||[];const canApprove=getNextApprover(status,user.role);return `<div class="card" style="margin-bottom:16px;"><div style="display:flex;justify-content:space-between;align-items:flex-start;"><div><div style="font-weight:600;color:var(--text-100);font-size:14px;">${o.sites?.name||`Site ${o.site_id}`} · ${items.length} item(s)</div><div style="color:var(--text-200);font-size:12px;margin-top:4px;">${o.supplier?`Supplier: ${o.supplier} · `:""}${new Date(o.created_at).toLocaleDateString("en-KE")}</div></div><div style="text-align:right;">${o.total_amount?`<div style="font-size:18px;font-weight:700;color:var(--gold);">KES ${Number(o.total_amount).toLocaleString()}</div>`:""}<span style="font-size:11px;color:var(--text-300);">${status.replace(/_/g," ")}</span></div></div><div style="margin-top:12px;background:var(--bg-700);border-radius:8px;padding:12px;">${items.map(i=>`<div style="display:flex;justify-content:space-between;font-size:12px;color:var(--text-200);margin-bottom:4px;"><span>${i.name||i.material_name||"Item"}</span><span>${i.quantity||1} ${i.unit||""} ${i.unit_price?`@ KES ${Number(i.unit_price).toLocaleString()}`:""}</span></div>`).join("")}</div>${o.approval_chain?.length?`<div style="margin-top:10px;font-size:11px;color:var(--text-300);">Approved by: ${o.approval_chain.map(a=>`${a.by} (${a.role})`).join(" → ")}</div>`:""}${canApprove?`<div style="margin-top:12px;display:flex;gap:8px;"><button onclick="window._procApprove('${o.id}','${status}')" class="btn btn-gold" style="font-size:12px;padding:8px 20px;">✓ Approve</button><button onclick="window._procReject('${o.id}')" class="btn btn-ghost" style="font-size:12px;padding:8px 16px;color:var(--red);">Reject</button></div>`:""}</div>`;}).join("");
    window._procApprove=(id,currentStatus)=>advanceProcurement(id,currentStatus,user);
    window._procReject=(id)=>changeProcurementStatus(id,"rejected",user);
  } catch(err){list.innerHTML=`<p style="color:var(--red);">Error: ${err.message}</p>`;}
}

function getNextApprover(status,role){const flow={pending:["project_manager","admin"],pm_approved:["asset_manager","admin"],am_approved:["finance","admin"],finance_approved:["procurement_officer","asset_manager","admin"]};return(flow[status]||[]).includes(role);}

async function advanceProcurement(id,currentStatus,user) {
  const idx=PROCUREMENT_FLOW.indexOf(currentStatus);const nextStatus=PROCUREMENT_FLOW[idx+1];if(!nextStatus){showToast("Already at final status","info");return;}
  const chainEntry={by:user.name,role:user.role,at:new Date().toISOString()};
  try {
    const curRes=await fetch(`${SUPABASE_URL}/rest/v1/procurement?id=eq.${id}&select=approval_chain,items,site_id`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`}});const [cur]=await curRes.json();const chain=Array.isArray(cur?.approval_chain)?[...cur.approval_chain,chainEntry]:[chainEntry];const patch={status:nextStatus,approval_chain:chain};
    if(nextStatus==="delivered"&&Array.isArray(cur?.items)){const siteId=cur.site_id;for(const item of cur.items){const itemName=item.name||item.material_name;const itemQty=parseFloat(item.quantity)||0;if(!itemName||itemQty<=0)continue;const chk=await fetch(`${SUPABASE_URL}/rest/v1/stock?site_id=eq.${siteId}&material_name=eq.${encodeURIComponent(itemName)}&limit=1`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`}});const existing=await chk.json();if(Array.isArray(existing)&&existing.length){const s=existing[0];await fetch(`${SUPABASE_URL}/rest/v1/stock?id=eq.${s.id}`,{method:"PATCH",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`},body:JSON.stringify({quantity:(s.quantity||0)+itemQty,unit_price:item.unit_price||s.unit_price,last_updated:new Date().toISOString(),updated_by:user.id})});}else{await fetch(`${SUPABASE_URL}/rest/v1/stock`,{method:"POST",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,Prefer:"return=minimal"},body:JSON.stringify({site_id:siteId,material_name:itemName,quantity:itemQty,unit:item.unit||"Pcs",unit_price:item.unit_price||0,updated_by:user.id})});}}}
    await fetch(`${SUPABASE_URL}/rest/v1/procurement?id=eq.${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`},body:JSON.stringify(patch)});
    await logAudit({action:"procurement_approved",module:"procurement",record_id:id,before:{status:currentStatus},after:{status:nextStatus,approver:user.name}});showToast(`Approved → ${nextStatus.replace(/_/g," ")}${nextStatus==="delivered"?" (stock added)":""}`,"success");
  } catch(err){showToast(`Error: ${err.message}`,"error");}
}

async function changeProcurementStatus(id,status,user) {
  try { await fetch(`${SUPABASE_URL}/rest/v1/procurement?id=eq.${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`},body:JSON.stringify({status})}); await logAudit({action:`procurement_${status}`,module:"procurement",record_id:id}); showToast(`Request ${status}`,"success"); } catch(err){showToast(`Error: ${err.message}`,"error");}
}

function openProcurementModal(user,siteFilter) {
  let items=[{name:"",quantity:1,unit:"Pcs",unit_price:null}];
  const renderItems=()=>{const el=document.getElementById("proc-items");if(!el)return;el.innerHTML=items.map((item,i)=>`<div style="display:grid;grid-template-columns:1fr auto auto auto 24px;gap:8px;margin-bottom:8px;"><input type="text" value="${item.name}" onchange="window._procUpdateItem(${i},'name',this.value)" placeholder="Material" style="background:var(--bg-700);border:1px solid var(--border);border-radius:6px;padding:8px;color:var(--text-100);font-size:12px;"><input type="number" value="${item.quantity}" onchange="window._procUpdateItem(${i},'quantity',parseFloat(this.value))" style="width:70px;background:var(--bg-700);border:1px solid var(--border);border-radius:6px;padding:8px;color:var(--text-100);font-size:12px;"><input type="text" value="${item.unit}" onchange="window._procUpdateItem(${i},'unit',this.value)" placeholder="Unit" style="width:55px;background:var(--bg-700);border:1px solid var(--border);border-radius:6px;padding:8px;color:var(--text-100);font-size:12px;"><input type="number" value="${item.unit_price||''}" onchange="window._procUpdateItem(${i},'unit_price',parseFloat(this.value))" placeholder="Price" style="width:85px;background:var(--bg-700);border:1px solid var(--border);border-radius:6px;padding:8px;color:var(--text-100);font-size:12px;"><button onclick="window._procRemoveItem(${i})" style="background:transparent;border:none;color:var(--red);cursor:pointer;">×</button></div>`).join("");};
  window._procUpdateItem=(i,f,v)=>{items[i][f]=v;};window._procRemoveItem=(i)=>{items.splice(i,1);renderItems();};window._procAddItem=()=>{items.push({name:"",quantity:1,unit:"Pcs",unit_price:null});renderItems();};
  showModal(`<h2 style="margin-bottom:20px;">New Purchase Request</h2><div style="display:flex;flex-direction:column;gap:16px;"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;"><div><label style="color:var(--text-300);font-size:12px;text-transform:uppercase;">Site</label><select id="proc-site" style="width:100%;margin-top:6px;background:var(--bg-700);border:1px solid var(--border);border-radius:8px;padding:10px;color:var(--text-100);">${SITES.filter(s=>siteFilter.includes(s.id)).map(s=>`<option value="${s.id}">${s.name}</option>`).join("")}</select></div><div><label style="color:var(--text-300);font-size:12px;text-transform:uppercase;">Supplier (optional)</label><input id="proc-supplier" type="text" style="width:100%;margin-top:6px;background:var(--bg-700);border:1px solid var(--border);border-radius:8px;padding:10px;color:var(--text-100);"></div></div><div><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;"><label style="color:var(--text-300);font-size:12px;text-transform:uppercase;">Items</label><button onclick="window._procAddItem()" style="background:transparent;border:1px solid var(--border);border-radius:6px;padding:4px 10px;color:var(--gold);cursor:pointer;font-size:11px;">+ Add Item</button></div><div id="proc-items"></div></div><div><label style="color:var(--text-300);font-size:12px;text-transform:uppercase;">Notes</label><textarea id="proc-notes" rows="2" style="width:100%;margin-top:6px;background:var(--bg-700);border:1px solid var(--border);border-radius:8px;padding:10px;color:var(--text-100);resize:none;"></textarea></div><div style="display:flex;gap:12px;"><button onclick="window._procSubmit()" class="btn btn-gold" style="flex:1;">Submit for Approval</button><button onclick="window._closeModal()" class="btn btn-ghost">Cancel</button></div></div>`);
  renderItems();
  window._procSubmit=async()=>{const siteId=parseInt(document.getElementById("proc-site").value);const supplier=document.getElementById("proc-supplier").value.trim();const notes=document.getElementById("proc-notes").value.trim();if(!items.some(i=>i.name.trim())){showToast("Add at least one item","error");return;}const total=items.reduce((s,i)=>(i.quantity||0)*(i.unit_price||0)+s,0);try{const res=await fetch(`${SUPABASE_URL}/rest/v1/procurement`,{method:"POST",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,Prefer:"return=representation"},body:JSON.stringify({site_id:siteId,requested_by:user.id,items:items.filter(i=>i.name.trim()),supplier:supplier||null,notes:notes||null,total_amount:total||null,status:"pending",approval_chain:[]})});if(!res.ok) throw new Error(await res.text());const [saved]=await res.json();await logAudit({action:"procurement_created",module:"procurement",record_id:saved.id});closeModal();showToast("Purchase request submitted","success");}catch(err){showToast(`Error: ${err.message}`,"error");}};
}
