// CDL — modules/users.js
import { SUPABASE_URL, SUPABASE_ANON_KEY, SITES } from "../config.js";
import { ROLES, SITE_MANAGERS } from "./roles.js";
import { logAudit } from "./audit_core.js";
import { showToast, showModal, closeModal } from "../app.js";

const ROLE_RANK={company_owner:10,admin:9,ceo:8,asset_manager:7,finance:6,office_manager:5,store_manager:5,site_overseer:4,project_manager:4,procurement_officer:3,transfer_officer:3,data_holder:3,engineer:2,storekeeper_local:1,storekeeper_import:1,storekeeper_scaffolding:1};
function canManageUsers(user){return["admin","company_owner","ceo","asset_manager"].includes(user.role);}
function canManageSites(user){return SITE_MANAGERS.includes(user.role);}
function canCreateRole(user,targetRole){return(ROLE_RANK[user.role]||0)>=(ROLE_RANK[targetRole]||0);}
function creatableRoles(user){return Object.keys(ROLES).filter(r=>canCreateRole(user,r));}

export async function renderUsers(container,user){
  if(!canManageUsers(user)&&!canManageSites(user)){container.innerHTML=`<div class="card" style="padding:40px;text-align:center;color:var(--red);">⛔ You do not have access to this section.</div>`;return;}
  const tabs=[];if(canManageUsers(user))tabs.push({key:"users",label:"👥 Users"});if(canManageSites(user))tabs.push({key:"sites",label:"🏗 Sites"});if(["admin","company_owner"].includes(user.role))tabs.push({key:"roles",label:"🔐 Role Viewer"});
  container.innerHTML=`<div style="margin-bottom:24px;"><h1 style="font-size:24px;font-weight:700;color:var(--text-100);">Administration</h1><p style="color:var(--text-200);font-size:14px;margin-top:4px;">Manage users, sites and roles</p></div><div style="display:flex;gap:4px;margin-bottom:24px;">${tabs.map((t,i)=>`<button id="adm-tab-${t.key}" onclick="window._admSwitch('${t.key}')" style="padding:8px 20px;border-radius:8px;border:none;cursor:pointer;font-size:13px;font-weight:500;${i===0?"background:var(--gold);color:#0a0c10;":"background:var(--bg-600);color:var(--text-200);"}">${t.label}</button>`).join("")}</div><div id="adm-panel"></div>`;
  const tabKeys=tabs.map(t=>t.key);
  window._admSwitch=(key)=>{tabKeys.forEach(k=>{const b=document.getElementById(`adm-tab-${k}`);if(b){b.style.background=k===key?"var(--gold)":"var(--bg-600)";b.style.color=k===key?"#0a0c10":"var(--text-200)";}});if(key==="users")loadUsersPanel(user);else if(key==="sites")loadSitesPanel(user);else loadRolesPanel(user);};
  if(tabKeys[0]==="users")loadUsersPanel(user);else if(tabKeys[0]==="sites")loadSitesPanel(user);
}

async function loadUsersPanel(currentUser){
  const panel=document.getElementById("adm-panel");panel.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;"><span style="color:var(--text-300);font-size:13px;">You can create roles up to: <strong style="color:var(--gold);">${ROLES[currentUser.role]?.label}</strong></span><button onclick="window._admOpenUserForm(null)" class="btn btn-gold">+ Add User</button></div><div id="users-table"><div class="spinner" style="margin:60px auto;"></div></div>`;
  window._admOpenUserForm=(u)=>userFormModal(currentUser,u);
  await fetchUsers(currentUser);
}

async function fetchUsers(currentUser){
  const el=document.getElementById("users-table");if(!el)return;
  try{
    const res=await fetch(`${SUPABASE_URL}/rest/v1/users?select=*&order=name.asc&limit=200`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`}});const users=await res.json();
    el.innerHTML=`<div class="card" style="overflow-x:auto;"><table style="width:100%;border-collapse:collapse;font-size:13px;"><thead><tr style="border-bottom:1px solid var(--border);">${["Name","Email","Role","Sites","Status","Actions"].map(h=>`<th style="text-align:left;padding:10px 8px;color:var(--text-400);font-weight:500;">${h}</th>`).join("")}</tr></thead><tbody>${users.map(u=>{const roleInfo=ROLES[u.role]||{};const rank=ROLE_RANK[u.role]||0;const myRank=ROLE_RANK[currentUser.role]||0;const canEdit=myRank>=rank||currentUser.role==="admin";const siteNames=(u.site_ids||[]).map(id=>SITES.find(s=>s.id===id)?.name||`#${id}`).join(", ")||"All";return `<tr style="border-bottom:1px solid rgba(30,35,48,0.5);"><td style="padding:10px 8px;font-weight:500;color:var(--text-100);">${u.name}</td><td style="padding:10px 8px;color:var(--text-200);">${u.email}</td><td style="padding:10px 8px;"><span style="padding:2px 10px;border-radius:12px;font-size:11px;background:rgba(200,169,110,0.1);color:var(--gold);">${roleInfo.label||u.role}</span></td><td style="padding:10px 8px;color:var(--text-200);font-size:12px;max-width:160px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;" title="${siteNames}">${siteNames}</td><td style="padding:10px 8px;"><span style="padding:2px 8px;border-radius:12px;font-size:11px;background:${u.is_active?"rgba(46,160,67,0.15)":"rgba(231,76,60,0.15)"};color:${u.is_active?"var(--green)":"var(--red)"};">${u.is_active?"Active":"Inactive"}</span></td><td style="padding:10px 8px;display:flex;gap:6px;">${canEdit?`<button onclick="window._admOpenUserForm(${JSON.stringify(u).replace(/"/g,"&quot;")})" style="background:transparent;border:1px solid var(--border);border-radius:6px;padding:4px 10px;color:var(--text-200);cursor:pointer;font-size:12px;">Edit</button><button onclick="window._admToggleUser('${u.id}',${u.is_active})" style="background:transparent;border:1px solid var(--border);border-radius:6px;padding:4px 10px;cursor:pointer;font-size:12px;color:${u.is_active?"var(--red)":"var(--green)"};">${u.is_active?"Disable":"Enable"}</button>`:"<span style='color:var(--text-300);font-size:12px;'>–</span>"}</td></tr>`;}).join("")}</tbody></table></div>`;
    window._admToggleUser=async(id,isActive)=>{try{await fetch(`${SUPABASE_URL}/rest/v1/users?id=eq.${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`},body:JSON.stringify({is_active:!isActive})});await logAudit({action:isActive?"user_disabled":"user_enabled",module:"admin",record_id:id});showToast(`User ${isActive?"disabled":"enabled"}`,"success");fetchUsers(currentUser);}catch(e){showToast(e.message,"error");}};
  }catch(e){el.innerHTML=`<p style="color:var(--red);">Error: ${e.message}</p>`;}
}

function userFormModal(currentUser,editUser){
  const isEdit=!!editUser;const allowedRoles=creatableRoles(currentUser);
  showModal(`<h2 style="margin-bottom:20px;">${isEdit?"Edit":"New"} User</h2><div style="display:flex;flex-direction:column;gap:14px;"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;"><div><label style="color:var(--text-300);font-size:11px;text-transform:uppercase;letter-spacing:.5px;">Full Name</label><input id="uf-name" value="${editUser?.name||""}" type="text" style="width:100%;margin-top:5px;background:var(--bg-700);border:1px solid var(--border);border-radius:8px;padding:10px;color:var(--text-100);"></div><div><label style="color:var(--text-300);font-size:11px;text-transform:uppercase;letter-spacing:.5px;">Email</label><input id="uf-email" value="${editUser?.email||""}" type="email" style="width:100%;margin-top:5px;background:var(--bg-700);border:1px solid var(--border);border-radius:8px;padding:10px;color:var(--text-100);"></div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;"><div><label style="color:var(--text-300);font-size:11px;text-transform:uppercase;letter-spacing:.5px;">Role</label><select id="uf-role" style="width:100%;margin-top:5px;background:var(--bg-700);border:1px solid var(--border);border-radius:8px;padding:10px;color:var(--text-100);">${allowedRoles.map(r=>`<option value="${r}" ${editUser?.role===r?"selected":""}>${ROLES[r]?.label||r}</option>`).join("")}</select></div><div><label style="color:var(--text-300);font-size:11px;text-transform:uppercase;letter-spacing:.5px;">Password ${isEdit?"(blank = keep)":""}</label><input id="uf-pw" type="password" style="width:100%;margin-top:5px;background:var(--bg-700);border:1px solid var(--border);border-radius:8px;padding:10px;color:var(--text-100);"></div></div><div style="display:flex;flex-direction:column;gap:4px;"><label style="color:var(--text-300);font-size:11px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px;">Position / Title</label><input id="uf-position" value="${editUser?.position||""}" type="text" placeholder="e.g. Site Manager, Procurement Officer" style="background:var(--bg-700);border:1px solid var(--border);border-radius:8px;padding:10px;color:var(--text-100);font-size:13px;"></div><div><label style="color:var(--text-300);font-size:11px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px;display:block;">Assigned Sites</label><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;">${SITES.map(s=>`<label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:12px;color:var(--text-200);"><input type="checkbox" value="${s.id}" class="uf-site" ${(editUser?.site_ids||[]).includes(s.id)?"checked":""} style="accent-color:var(--gold);">${s.name}</label>`).join("")}</div></div><div style="display:flex;gap:10px;margin-top:4px;"><button onclick="window._admSaveUser('${editUser?.id||""}')" class="btn btn-gold" style="flex:1;">${isEdit?"Save Changes":"Create User"}</button><button onclick="window._closeModal()" class="btn btn-ghost">Cancel</button></div></div>`);
  window._admSaveUser=async(uid)=>{const name=document.getElementById("uf-name").value.trim();const email=document.getElementById("uf-email").value.trim();const role=document.getElementById("uf-role").value;const pw=document.getElementById("uf-pw").value;const sites=[...document.querySelectorAll(".uf-site:checked")].map(c=>parseInt(c.value));if(!name||!email){showToast("Name and email required","error");return;}if(!canCreateRole(currentUser,role)){showToast("You cannot assign that role","error");return;}const position=document.getElementById("uf-position").value.trim();const payload={name,email,role,position,site_ids:sites,is_active:true,...(pw?{password_hash:pw}:{})};try{if(uid){await fetch(`${SUPABASE_URL}/rest/v1/users?id=eq.${uid}`,{method:"PATCH",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`},body:JSON.stringify(payload)});await logAudit({action:"user_updated",module:"admin",record_id:uid,after:payload});}else{const r=await fetch(`${SUPABASE_URL}/rest/v1/users`,{method:"POST",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,Prefer:"return=representation"},body:JSON.stringify(payload)});if(!r.ok) throw new Error(await r.text());const [saved]=await r.json();await logAudit({action:"user_created",module:"admin",record_id:saved.id,after:payload});}closeModal();showToast(`User ${uid?"updated":"created"}`,"success");fetchUsers(currentUser);}catch(e){showToast(e.message,"error");}};
}

async function loadSitesPanel(user){
  const panel=document.getElementById("adm-panel");panel.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;"><span style="color:var(--text-300);font-size:13px;">Manage construction sites · ${SITES.length} total</span><button onclick="window._admOpenSiteForm(null)" class="btn btn-gold">+ Add Site</button></div><div id="sites-table"><div class="spinner" style="margin:60px auto;"></div></div>`;
  window._admOpenSiteForm=(s)=>siteFormModal(user,s);await fetchSites(user);
}

async function fetchSites(user){
  const el=document.getElementById("sites-table");if(!el)return;
  try{const res=await fetch(`${SUPABASE_URL}/rest/v1/sites?select=*&order=id.asc`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`}});const sites=await res.json();el.innerHTML=`<div class="card" style="overflow-x:auto;"><table style="width:100%;border-collapse:collapse;font-size:13px;"><thead><tr style="border-bottom:1px solid var(--border);">${["#","Name","Type","Status","Actions"].map(h=>`<th style="text-align:left;padding:10px 8px;color:var(--text-400);font-weight:500;">${h}</th>`).join("")}</tr></thead><tbody>${sites.map(s=>`<tr style="border-bottom:1px solid rgba(30,35,48,0.5);"><td style="padding:10px 8px;color:var(--text-300);">${s.id}</td><td style="padding:10px 8px;font-weight:500;color:var(--text-100);">${s.name}</td><td style="padding:10px 8px;"><span style="padding:2px 10px;border-radius:12px;font-size:11px;background:rgba(61,142,248,0.1);color:var(--blue);">${s.type||"–"}</span></td><td style="padding:10px 8px;"><span style="padding:2px 10px;border-radius:12px;font-size:11px;background:${s.is_active?"rgba(46,160,67,0.15)":"rgba(231,76,60,0.15)"};color:${s.is_active?"var(--green)":"var(--red)"};">${s.is_active?"Active":"Inactive"}</span></td><td style="padding:10px 8px;display:flex;gap:6px;"><button onclick="window._admOpenSiteForm(${JSON.stringify(s).replace(/"/g,"&quot;")})" style="background:transparent;border:1px solid var(--border);border-radius:6px;padding:4px 10px;color:var(--text-200);cursor:pointer;font-size:12px;">Edit</button><button onclick="window._admToggleSite('${s.id}',${s.is_active})" style="background:transparent;border:1px solid var(--border);border-radius:6px;padding:4px 10px;cursor:pointer;font-size:12px;color:${s.is_active?"var(--red)":"var(--green)"};">${s.is_active?"Deactivate":"Activate"}</button></td></tr>`).join("")}</tbody></table></div>`;window._admToggleSite=async(id,isActive)=>{try{await fetch(`${SUPABASE_URL}/rest/v1/sites?id=eq.${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`},body:JSON.stringify({is_active:!isActive})});await logAudit({action:isActive?"site_deactivated":"site_activated",module:"admin",record_id:id});showToast(`Site ${isActive?"deactivated":"activated"}`,"success");fetchSites(user);}catch(e){showToast(e.message,"error");}};}catch(e){el.innerHTML=`<p style="color:var(--red);">Error: ${e.message}</p>`;}
}

function siteFormModal(user,site){
  const isEdit=!!site;showModal(`<h2 style="margin-bottom:20px;">${isEdit?"Edit":"New"} Site</h2><div style="display:flex;flex-direction:column;gap:14px;"><div><label style="color:var(--text-300);font-size:11px;text-transform:uppercase;letter-spacing:.5px;">Site Name</label><input id="sf-name" value="${site?.name||""}" style="width:100%;margin-top:5px;background:var(--bg-700);border:1px solid var(--border);border-radius:8px;padding:10px;color:var(--text-100);"></div><div><label style="color:var(--text-300);font-size:11px;text-transform:uppercase;letter-spacing:.5px;">Type</label><select id="sf-type" style="width:100%;margin-top:5px;background:var(--bg-700);border:1px solid var(--border);border-radius:8px;padding:10px;color:var(--text-100);"><option value="residential" ${site?.type==="residential"?"selected":""}>Residential</option><option value="commercial" ${site?.type==="commercial"?"selected":""}>Commercial</option><option value="warehouse" ${site?.type==="warehouse"?"selected":""}>Warehouse</option></select></div><div style="display:flex;gap:10px;margin-top:4px;"><button onclick="window._admSaveSite('${site?.id||""}')" class="btn btn-gold" style="flex:1;">${isEdit?"Save Changes":"Create Site"}</button><button onclick="window._closeModal()" class="btn btn-ghost">Cancel</button></div></div>`);
  window._admSaveSite=async(sid)=>{const name=document.getElementById("sf-name").value.trim();const type=document.getElementById("sf-type").value;if(!name){showToast("Site name required","error");return;}try{if(sid){await fetch(`${SUPABASE_URL}/rest/v1/sites?id=eq.${sid}`,{method:"PATCH",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`},body:JSON.stringify({name,type})});await logAudit({action:"site_updated",module:"admin",after:{name,type}});}else{const r=await fetch(`${SUPABASE_URL}/rest/v1/sites`,{method:"POST",headers:{"Content-Type":"application/json",apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,Prefer:"return=representation"},body:JSON.stringify({name,type,is_active:true})});if(!r.ok) throw new Error(await r.text());const [saved]=await r.json();await logAudit({action:"site_created",module:"admin",record_id:saved.id,after:{name,type}});}closeModal();showToast(`Site ${sid?"updated":"created"}`,"success");fetchSites(user);}catch(e){showToast(e.message,"error");}};
}

function loadRolesPanel(user){
  const panel=document.getElementById("adm-panel");panel.innerHTML=`<div class="card"><h3 style="margin-bottom:20px;color:var(--text-100);">All 16 Roles & Permissions</h3><div style="overflow-x:auto;"><table style="width:100%;border-collapse:collapse;font-size:12px;"><thead><tr style="border-bottom:1px solid var(--border);">${["Role","Scope","AI/Day","Key Permissions"].map(h=>`<th style="text-align:left;padding:10px 8px;color:var(--text-400);font-weight:500;">${h}</th>`).join("")}</tr></thead><tbody>${Object.entries(ROLES).map(([key,r])=>{const perms=[r.canManageSites&&"Manage Sites",r.canManageUsers&&"Manage Users",r.canApproveProcurement&&"Approve Procurement",r.canApproveTransfers&&"Approve Transfers",r.canUnlockOpeningBalance&&"Unlock Balance",r.canSeeBudget&&"See Budget",r.canVerifyGRN&&"Verify GRN",r.canScanGRN&&"Scan GRN",r.canEditInventory===false&&"NO Inventory Edit"].filter(Boolean);return `<tr style="border-bottom:1px solid rgba(30,35,48,0.5);"><td style="padding:10px 8px;"><span style="padding:2px 10px;border-radius:12px;font-size:11px;background:${r.color||"#333"}22;color:${r.color||"var(--text-300)"};">${r.label}</span></td><td style="padding:10px 8px;color:var(--text-200);">${r.siteScope||"assigned"}</td><td style="padding:10px 8px;color:var(--gold);">${r.aiMsgsPerDay===Infinity?"∞":r.aiMsgsPerDay||0}</td><td style="padding:10px 8px;color:var(--text-200);">${perms.length?perms.map(p=>`<span style="display:inline-block;margin:2px;padding:1px 7px;border-radius:10px;font-size:11px;background:${p.startsWith("NO")?"rgba(231,76,60,0.1)":"rgba(200,169,110,0.08)"};color:${p.startsWith("NO")?"var(--red)":"var(--text-200)"};">${p}</span>`).join(""):'<span style="color:var(--text-300);">Standard access</span>'}</td></tr>`;}).join("")}</tbody></table></div></div>`;
}
