// AUTO-GENERATED by scripts/inject-env.js â€” do not edit manually
// Values come from Netlify environment variables / .env file
// Never commit this file with real secrets â€” it is regenerated on each build

export const GEMINI_KEYS = ["AIzaSyAICinEgwTKHLQqVV8K4bEVhKOWCWIB348"];
export const GEMINI_MODEL_PRIMARY = "gemini-3.6-flash";
export const GEMINI_MODEL_FALLBACK = "gemini-3.6-flash";
