@echo off
echo Starting continuous CDL ERP testing...
:loop
echo [%date% %time%] Running test cycle...
node skyvern-targeted-test.mjs
echo [%date% %time%] Test cycle complete. Waiting 5 minutes...
timeout /t 300 /nobreak
goto loop