// Build-time env injection for static site
// Reads NETLIFY_ env vars (set in Netlify dashboard) and .env file
const fs = require('fs');
const path = require('path');

// Load .env file for local development
const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  for (const line of envContent.split('\n')) {
    const match = line.match(/^([A-Z_]+)=(.*)$/);
    if (match && !process.env[match[1]]) {
      process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, '');
    }
  }
}

const keysStr = process.env.GEMINI_API_KEY || '';
let keys = keysStr.split(',').filter(k => k.trim());
if (keys.length === 0) {
  // Fallback for local dev â€” remove when deploying with proper env vars
  keys.push('AIzaSyAICinEgwTKHLQqVV8K4bEVhKOWCWIB348');
}

const envConfig = `// AUTO-GENERATED by scripts/inject-env.js â€” do not edit manually
// Values come from Netlify environment variables / .env file
// Never commit this file with real secrets â€” it is regenerated on each build

export const GEMINI_KEYS = ${JSON.stringify(keys)};
export const GEMINI_MODEL_PRIMARY = "${process.env.GEMINI_MODEL_PRIMARY || 'gemini-3.6-flash'}";
export const GEMINI_MODEL_FALLBACK = "${process.env.GEMINI_MODEL_FALLBACK || 'gemini-3.6-flash'}";
`;

const outPath = path.join(__dirname, '..', 'config-env.js');
fs.writeFileSync(outPath, envConfig);
console.log('Generated config-env.js from environment variables');